version: '3.3'
services:
  test:
    build: .
    environment:
      - DYNAMODB_TABLE=items-test
      - IS_LOCAL_ENV=true
      - USERS_URL="https://qmk33jcqwh.execute-api.eu-west-2.amazonaws.com/giovanni/user"
    command: npm run test
    volumes:
      - ~/.aws/:/root/.aws/
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"